feat: Update CardLayout component [BLOX-166]
BloxiFi/bloxifi-fe pull request #100
Opened 2022-06-20 11:31 UTC by Kristina2103

# Pull Request Template

Feel free to remove any section (except the checklist) from this template.
But please try to fill in as much of this as possible.

## Description

Figma https://www.figma.com/file/8G6OqCH6vmpyreKf60KIcV/BloxiFi---public?node-id=47%3A130
## Type of change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
- [ ] This change requires a configuration update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.
Provide easily reproducible instructions.
List any relevant details for your test configuration.

## Checklist:

- [ ] I have performed a self-review of this code and spelling
- [ ] I have added comments in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Additional information

Include any additional information about these changes here.

For example, if you are making a visual change, please include BEFORE (if any) and AFTER screenshots.
A visual change could be just reordering some components on a page.
Any visual changes in the UI MUST provide these screenshots.

2022-06-20 16:21 UTC, aleksaToljic commented
/deploy storybook

2022-06-20 16:33 UTC, aleksaToljic requested changes

2022-06-20 16:33 UTC, aleksaToljic commented on packages/ui/src/styles/colors.ts
> +  borderLight: 'rgba(0,0,0,0.2)',
we need to add every color in light and dark objects. 
If I missed some new color that you added, please add it like this.

```tsx
light: {someColor: 'color'}
dark: {someColor: 'color'}
```

They should have the same naming (and initially the same color, but later on we will change  to `dark: {someColor: 'darkColor'}`

2022-06-20 17:45 UTC, Kristina2103 commented on packages/ui/src/styles/colors.ts
> +  borderLight: 'rgba(0,0,0,0.2)',
@aleksaToljic should I also change imports in components for those colors, to get the color of active theme mode  or just update light/dark objects for now?

2022-06-21 11:14 UTC, aleksaToljic commented on packages/ui/src/styles/colors.ts
> +  borderLight: 'rgba(0,0,0,0.2)',
well, on homePage, I used other approuch i fetched what theme we are currently using
https://styled-components.com/docs/advanced

2022-06-21 11:15 UTC, aleksaToljic commented on packages/ui/src/styles/colors.ts
> +  borderLight: 'rgba(0,0,0,0.2)',
although we should probably use a bit better approuch for this, but we can work with this for now, if you think of something better let me know.

2022-06-23 09:25 UTC, aleksaToljic approved these changes

2022-06-23 09:25 UTC, merged